language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libboost-all-dev

before_script:
  - cd ../..
  - git clone https://github.com/czipperz/vick czipperz/vick
  - cd czipperz/vick
  - mkdir -p plugins
  - cd plugins
  # customize me!
  - git clone https://github.com/czipperz/vick-move
  - cd ..

script:
  - ./testing.sh
