language: cpp

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo apt-get install -qq libboost-all-dev

before_script:
  - cd ../..
  - git clone https://github.com/czipperz/vick czipperz/vick
  - cd czipperz/vick
  - mkdir -p plugins
  - cd plugins
  # customize me!
  - git clone https://github.com/czipperz/vick-move
  - cd ..

script: make CXX=g++-4.8 test
